- src/Snak/PropertyValueSnak.php
> Simplify PropertyValueSnak::unserialize

- tests/unit/Claim/ClaimTest.php
- tests/unit/Statement/StatementTest.php
This is a small bit of refactoring and clean up (zero functional changes, as far as I'm aware of) split from #306.
> Clean up Claim/Statement Test

- RELEASE-NOTES.md
- src/Entity/Item.php
- src/Entity/Property.php
- src/Term/Fingerprint.php
- tests/unit/Entity/Diff/FingerprintPatcherTest.php
- tests/unit/Entity/EntityTest.php
- tests/unit/Entity/ItemTest.php
- tests/unit/Term/FingerprintTest.php
This is a split from #296, containing the non-controversial part.
> Allow constructing empty Fingerprint

- tests/unit/Statement/StatementListTest.php
Follow up to https://github.com/wmde/WikibaseDataModel/pull/289
> Enhance new StatementListTest test

- src/Snak/SnakList.php
- tests/unit/HashArray/HashArrayTest.php
- tests/unit/HashArray/HashArrayWithDuplicatesTest.php
- tests/unit/HashArray/HashArrayWithoutDuplicatesTest.php
- tests/unit/Snak/SnakListTest.php
This also drops and fixes some outdated tags.
> Make some doc tags more specific

- tests/unit/ReferenceTest.php
Not urgent. I just copy-pasted the test from #356 to be on the safe side.
> More constructor test cases in ReferenceTest

- src/Entity/EntityIdValue.php
I found the fact that this returns itself non-intuitive
in the first place...
> Fix @return doc of EntityIdValue::getValue

- tests/unit/Entity/EntityTest.php
- tests/unit/Entity/ItemTest.php
- tests/unit/Entity/PropertyTest.php
This is split from #317 to make it easier to review. Please merge ASAP.
> Drop unused EntityTest::makeClaims method

- tests/unit/Entity/Diff/EntityDiffTest.php
- tests/unit/Entity/ItemTest.php
- tests/unit/Statement/StatementListDifferTest.php
- tests/unit/Statement/StatementListTest.php
Same as #367, but for the master branch.
> Favor StatementList's argument list constructor

- RELEASE-NOTES.md
- WikibaseDataModel.php
- composer.json
Collection of what already changed and is going to change in the 3.x branch so we don't forget anything.
This is split from #317.
> Release 3.0.0

- tests/unit/Entity/Diff/EntityPatcherTest.php
- tests/unit/Entity/ItemTest.php
This patch
* reduces the number of `setId` calls
* reduces the usage of numeric ids.
> Reduce number of setId calls

- composer.json
Reverts wmde/WikibaseDataModel#390
> Revert "Don't access vendor/bin in composer ci"

- RELEASE-NOTES.md
- src/Reference.php
- src/ReferenceList.php
- tests/unit/ReferenceListTest.php
- tests/unit/ReferenceTest.php
> Ignore empty references when added to ReferenceList

- src/Entity/DispatchingEntityIdParser.php
This is split from #386 which is split from #346.
Tests are already there, see #402.
> Individual exceptions messages in DispatchingEntityIdParser

- .travis.yml
- README.md
- RELEASE-NOTES.md
- composer.json
- src/Entity/DispatchingEntityIdParser.php
- src/Entity/EntityIdValue.php
- src/Entity/Item.php
- src/Entity/Property.php
- src/Reference.php
- src/ReferenceList.php
- tests/unit/ByPropertyIdArrayTest.php
- tests/unit/ByPropertyIdGrouperTest.php
- tests/unit/Claim/ClaimGuidTest.php
- tests/unit/Entity/BasicEntityIdParserTest.php
- tests/unit/Entity/Diff/EntityDiffTest.php
- tests/unit/Entity/Diff/ItemDiffTest.php
- tests/unit/Entity/DispatchingEntityIdParserTest.php
- tests/unit/Entity/EntityTest.php
- tests/unit/ReferenceListTest.php
- tests/unit/ReferenceTest.php
- tests/unit/Snak/SnakListTest.php
- tests/unit/Statement/StatementTest.php
> Merge master into 3.0.x-dev

- tests/unit/Entity/ItemIdTest.php
- tests/unit/Entity/PropertyIdTest.php
I wonder why these methods never had tests.
> Increase test coverage for id classes

- src/Statement/StatementByGuidMap.php
- src/Statement/StatementList.php
- tests/unit/Statement/StatementByGuidMapTest.php
Pair programmed with @KaiNissen 
Tackles https://github.com/wmde/WikibaseDataModel/issues/304
> Added StatementByGuidMap

- src/ByPropertyIdArray.php
- src/Entity/Entity.php
- src/ReferenceList.php
- src/Statement/StatementList.php
- tests/unit/Entity/ItemTest.php
* Drop some not needed `@var` tags.
* Favor `=== null` over `is_null`.
* Some minor code style changes.
> Minor code styling bits

- src/Statement/StatementList.php
- tests/unit/Statement/StatementListTest.php
This is the opposite of what we discussed in #453.
I also moved the private getters to the top.
> More StatementList tests

- src/Snak/Snaks.php
First step of https://github.com/wmde/WikibaseDataModel/issues/240
> Deprecate Snaks interface

- .floo
- .flooignore
- .gitignore
Reverts wmde/WikibaseDataModel#418
> Revert "Add floobits config"

- RELEASE-NOTES.md
- WikibaseDataModel.php
- src/Snak/SnakList.php
- tests/unit/Snak/SnakListTest.php
[Bug: T104405](https://phabricator.wikimedia.org/T104405)
> Fix SnakList::orderByProperty

- src/Snak/DerivedPropertyValueSnak.php
- src/Snak/PropertyValueSnak.php
- tests/unit/Snak/DerivedPropertyValueSnakTest.php
Resubmission of #508 by @addshore which got merged prematurely and broke master
> Implement DeivedPropertyValueSnak

- src/Statement/ReferencedStatementFilter.php
- src/Statement/StatementFilter.php
- src/Statement/StatementList.php
- tests/unit/Statement/ReferencedStatementFilterTest.php
- tests/unit/Statement/StatementListTest.php
> Add filter method to StatementList

- RELEASE-NOTES.md
- src/Entity/Entity.php
- tests/unit/Entity/EntityTest.php
- tests/unit/Entity/ItemTest.php
Reverts wmde/WikibaseDataModel#518
> Revert "Remove Entity::copy"

- src/Entity/Entity.php
Reverts wmde/WikibaseDataModel#522
> Revert "Remove methods from Entity undeprecated in subclasses"

- src/Entity/EntityRedirect.php
- tests/unit/Entity/EntityRedirectTest.php
This is a copy and paste from Wikibase Lib
> Add EntityRedirect & Test

- src/Snak/DerivedPropertyValueSnak.php
- src/Statement/StatementByGuidMap.php
There is even a test for calling StatementByGuidMap with a Traversable. See StatementList for reference.
> Fix missing/incomplete PHPDoc tags

- src/Entity/BasicEntityIdParser.php
- src/Entity/DispatchingEntityIdParser.php
- src/Entity/EntityIdParser.php
- src/Entity/EntityIdParsingException.php
- tests/unit/Entity/BasicEntityIdParserTest.php
- tests/unit/Entity/DispatchingEntityIdParserTest.php
Fixes https://phabricator.wikimedia.org/T110344 | https://github.com/wmde/WikibaseDataModelServices/issues/55
> Move EntityIdParser back from DataModel Services

- RELEASE-NOTES.md
- src/Entity/Entity.php
- src/Entity/EntityDocument.php
This is part of the RFC on phabricator: https://phabricator.wikimedia.org/T110177
> Add isEmpty to EntityDocument

- RELEASE-NOTES.md
- WikibaseDataModel.php
> 4.3.0 release

- composer.json
- phpcs.xml
- phpmd.xml
- tests/unit/Entity/ItemTest.php
- tests/unit/Entity/PropertyTest.php
- tests/unit/Statement/StatementTest.php
This makes them match the already updated Wikibase DataModel Services ones.
> Update CS rules

- phpcs.xml
- tests/unit/Entity/EntityTest.php
- tests/unit/Entity/ItemTest.php
This is split from #565. All these additional rules are currently in our Wikibase.git rule set.
> Add and fix PHPCS FunctionSpacing rule

- phpcs.xml
- tests/unit/SiteLinkTest.php
> Fix newline issues according to PHPCS whitespace rules

- src/Entity/Entity.php
- src/ReferenceList.php
- src/Statement/StatementList.php
- tests/unit/ByPropertyIdArrayTest.php
- tests/unit/ReferenceListTest.php
- tests/unit/ReferenceTest.php
- tests/unit/Statement/StatementGuidTest.php
> Fix whitespace in if() and such

- src/Statement/ReferencedStatementFilter.php
This goes along with:
* https://github.com/wmde/WikibaseDataModelServices/pull/97
* https://gerrit.wikimedia.org/r/258124
* https://gerrit.wikimedia.org/r/257880
> Introduce constants for StatementGrouper names

- src/SiteLinkList.php
- tests/unit/ByPropertyIdArrayTest.php
- tests/unit/Entity/EntityTest.php
- tests/unit/SiteLinkListTest.php
- tests/unit/Statement/StatementGuidTest.php
This is split from #565, leaving no other code changes behind.
> Fix remaining minor whitespace issues

- src/ByPropertyIdArray.php
- src/Claim/Claims.php
- src/Entity/EntityIdValue.php
See https://gerrit.wikimedia.org/r/258941.
> No newline between @throws and @return

- composer.json
> Validate covers tags

- src/ByPropertyIdArray.php
- src/HashableObjectStorage.php
- src/Term/AliasGroupFallback.php
- tests/unit/Snak/PropertyValueSnakTest.php
… plus a few very minor details like splitting long lines.
> Add missing null type documentations

- src/Term/TermList.php
- tests/unit/Term/TermListTest.php
This is for discussion~~; do not merge.~~
https://groups.google.com/a/wikimedia.de/d/topic/wikimedia-de-tech/NTb6EyOVMCE/discussion
[Bug: T121433](https://phabricator.wikimedia.org/T121433)
> Filter out terms with empty string value in termlist

- src/ReferenceList.php
- src/Statement/Statement.php
- tests/unit/ReferenceListTest.php
Reverts wmde/WikibaseDataModel#500
> Revert "Make ReferenceList no longer extend SplObjectStorage "

- src/Entity/Entity.php
- src/Entity/Item.php
- src/Entity/Property.php
- src/Statement/StatementList.php
- tests/unit/Entity/EntityTest.php
> Remove getClaims/setClaims from all Entity classes

- RELEASE-NOTES.md
- src/ReferenceList.php
- tests/unit/ReferenceListTest.php
> Cleanup ReferenceList changes

- src/Entity/Property.php
- tests/unit/Entity/PropertyTest.php
> Fix major bug in Property::clear

- tests/unit/ReferenceListTest.php
This is split from #639, which got pretty big when I reworked it this morning. All tests in this patch here succeed with version 4.4.0 and 5.0.1 (would be good if you could try this again). I would like to rebase #639 when this is merged to make it much smaller and easier to review.
> Add more regression tests for 4.x vs. 5.x compatibility

- mediawiki-extension.json
> Set manifest_version in extension.json

- RELEASE-NOTES.md
- src/Statement/StatementListHolder.php
- src/Term/FingerprintHolder.php
As decided in [T126152](https://phabricator.wikimedia.org/T126152)
Bug: [T128362](https://phabricator.wikimedia.org/T128362)
> Deprecate Holder interfaces

- src/ByPropertyIdArray.php
Minimal patch that's guaranteed to not be a breaking change.
> Use PropertyIdProvider in ByPropertyIdArray

- RELEASE-NOTES.md
- src/Entity/EntityDocument.php
Pinging @Benestar. Feel free to tag the release.
> Release 5.1.0

- src/Entity/ItemId.php
- src/Entity/PropertyId.php
- tests/unit/Entity/ItemIdTest.php
- tests/unit/Entity/PropertyIdTest.php
[Bug: T133299](https://phabricator.wikimedia.org/T133299)
> Fix newline injection vector in EntityId validation

- RELEASE-NOTES.md
- WikibaseDataModel.php
- mediawiki-extension.json
[Bug: T133299](https://phabricator.wikimedia.org/T133299)
> Release 6.0.1

- RELEASE-NOTES.md
- WikibaseDataModel.php
- composer.json
- mediawiki-extension.json
- src/Entity/Item.php
- src/ReferenceList.php
- src/Term/Fingerprint.php
~~Note that this mentions #665 as it was already merged.~~ Done.
**Requires the following fixes before the actual release!**
* ~~https://gerrit.wikimedia.org/r/299517~~ Done.
* ~~https://gerrit.wikimedia.org/r/299553~~ Done.
* ~~https://gerrit.wikimedia.org/r/299555~~ Done.
> Release 6.1.0

- src/Entity/ItemId.php
- src/Entity/PropertyId.php
Reverts wmde/WikibaseDataModel#674
> Revert "Document usages of the Int32EntityId interface"

- docs/foreign-entity-ids.wiki
Based on https://phabricator.wikimedia.org/T133381 (enhanced copy-and-paste).
> Add Foreign Entity Ids specification

- tests/bootstrap.php
Also see:
- https://github.com/wmde/WikibaseDataModelServices/pull/98
- https://github.com/wmde/WikibaseInternalSerialization/pull/89
> Name ClassLoader object $classLoader

- src/Entity/Int32EntityId.php
- src/Entity/ItemId.php
- src/Entity/PropertyId.php
Resubmission of https://github.com/wmde/WikibaseDataModel/pull/674 by @thiemowmde
Please regard this as if it where the original PR. I accidentally merged it, and then reverted plus resubmitted to undo my mistake. This should have no bearing on further review.
> Document usages of the Int32EntityId interface

- tests/unit/Statement/StatementListTest.php
Follow up after #698 was merged, see the discussion there.
> Avoid numeric Property IDs in StatementListTest

- src/Entity/EntityIdValue.php
> Forward previous exception in EntityIdValue

- src/Entity/DispatchingEntityIdParser.php
This is a (non-failing) alternative for #736.
> Much more expressive exception in DispatchingEntityIdParser

- src/Entity/EntityIdValue.php
- src/Statement/StatementListHolder.php
This is documentation only and does not need an immediate release.
[Bug: T168681](https://phabricator.wikimedia.org/T168681)
> Clarify documentation of …::newFromArray

- src/Entity/Item.php
- src/Entity/Property.php
- tests/unit/Entity/ItemTest.php
- tests/unit/Entity/PropertyTest.php
> Do not let int as value in Item::setId and Property::setId

- RELEASE-NOTES.md
- WikibaseDataModel.php
- composer.json
Updated 7.x branch. I hope I did not miss any non-breaking change since 7.0.
> Release 7.1.0

- RELEASE-NOTES.md
- WikibaseDataModel.php
The change that recently got merged is a breaking change.
So it needs a major release.
> Update release notes for 8.0.0

- src/Snak/SnakList.php
- tests/unit/Snak/SnakListTest.php
This is an alternative for #761. Please see the description there.
> Heavily optimize SnakList::moveSnaksToBottom

- RELEASE-NOTES.md
- WikibaseDataModel.php
- composer.json
- src/Entity/DispatchingEntityIdParser.php
- src/Snak/SnakList.php
- tests/unit/Snak/SnakListTest.php
@mariushoch, please review this carefully. The master branch contains other changes to the SnakList class and I'm really not sure if we can backport this so easily. On the other hand, if all tests succeed, why not?
[Bug: T177486](https://phabricator.wikimedia.org/T177486)
> Release 7.2.0

- RELEASE-NOTES.md
- WikibaseDataModel.php
- composer.json
Not sure if protected stuff must be part of release notes but it was not me who added it :)
> Release 7.3.0

- RELEASE-NOTES.md
- src/Entity/EntityId.php
- src/Entity/ItemId.php
- src/Entity/PropertyId.php
- tests/fixtures/CustomEntityId.php
> Sync with 7.3: Optimize EntityId::getRepositoryName and ::getLocalPart

- README.md
- RELEASE-NOTES.md
- WikibaseDataModel.php
The new commits between 7.3.0 and 7.x can be seen @ https://github.com/wmde/WikibaseDataModel/compare/7.3.0...7.x
> Prepare for 7.4.0 release on 7.x. branch

- src/Entity/EntityDocument.php
- src/Entity/Item.php
- src/Entity/Property.php
- tests/unit/Entity/ItemTest.php
- tests/unit/Entity/PropertyTest.php
This reverts commit 73e2db3272f7e45924ff075eb6b1e5b52f272c6c.
> Revert "Add clear method to EntityDocument (#776)"

- RELEASE-NOTES.md
- composer.json
- src/Term/TermList.php
- tests/unit/Term/TermListTest.php
Follow-up-ish to https://github.com/wmde/WikibaseDataModel/pull/788
> Take iterable in TermList constructor

- README.md
- RELEASE-NOTES.md
- composer.json
- src/Entity/EntityDocument.php
This by reverting the ClearableEntity change which is causing the problems.
See https://phabricator.wikimedia.org/T206325
> Make DataModel usable in Wikibase again

- src/SiteLinkList.php
- tests/unit/SiteLinkListTest.php
Like we just did with TermList
> Allow iterable in SiteLinkList constructor

- src/Entity/EntityRedirect.php
- tests/unit/Entity/EntityRedirectTest.php
[Bug: T214920](https://phabricator.wikimedia.org/T214920)
> Prevent redirecting an entity to itself

- RELEASE-NOTES.md
- composer.json
- src/SiteLinkList.php
- src/Term/TermList.php
- tests/unit/SiteLinkListTest.php
- tests/unit/Term/TermListTest.php
Just ran into this while working on new term store stuff
> Throw exception rather than ignoring non-iterable

- RELEASE-NOTES.md
- composer.json
preparations for 9.5.0 release
> Date relnotes for 9.5.0

- RELEASE-NOTES.md
Made a mess with the dates yesterday.
> Update release date 9.5.0

- .phpcs.xml
- RELEASE-NOTES.md
- composer.json
- src/ReferenceList.php
- src/Statement/Statement.php
- src/Statement/StatementList.php
- tests/unit/Entity/EntityIdTest.php
- tests/unit/Entity/EntityIdValueTest.php
- tests/unit/Entity/EntityRedirectTest.php
- tests/unit/Entity/ItemIdSetTest.php
- tests/unit/Entity/ItemIdTest.php
- tests/unit/Entity/PropertyIdTest.php
- tests/unit/Entity/PropertyTest.php
- tests/unit/Internal/MapValueHasherTest.php
- tests/unit/ReferenceTest.php
- tests/unit/SiteLinkTest.php
- tests/unit/Snak/DerivedPropertyValueSnakTest.php
- tests/unit/Snak/PropertyNoValueSnakTest.php
- tests/unit/Snak/PropertySomeValueSnakTest.php
- tests/unit/Snak/PropertyValueSnakTest.php
- tests/unit/Snak/SnakListTest.php
- tests/unit/Snak/SnakTest.php
- tests/unit/Snak/TypedSnakTest.php
- tests/unit/Statement/StatementByGuidMapTest.php
- tests/unit/Statement/StatementGuidTest.php
- tests/unit/Statement/StatementListTest.php
- tests/unit/Statement/StatementTest.php
- tests/unit/Term/TermListTest.php
See individual commit messages for details and [T253636](https://phabricator.wikimedia.org/T253636) for motivation.
> Update wikibase/wikibase-codesniffer to 1.2.0

- .phpcs.xml
- composer.json
- src/Statement/Statement.php
> Replace wikibase-codesniffer with mediawiki-codesniffer

- RELEASE-NOTES.md
- composer.json
- src/Entity/EntityDocument.php
- src/Entity/EntityId.php
- src/Entity/EntityIdValue.php
- src/Entity/ItemIdSet.php
- src/Reference.php
- src/ReferenceList.php
- src/SiteLink.php
- src/SiteLinkList.php
- src/Snak/Snak.php
- src/Snak/SnakList.php
- src/Snak/SnakObject.php
- src/Statement/Statement.php
- src/Statement/StatementGuid.php
- src/Statement/StatementList.php
- src/Term/AliasGroup.php
- src/Term/AliasGroupFallback.php
- src/Term/AliasGroupList.php
- src/Term/Fingerprint.php
- src/Term/Term.php
- src/Term/TermFallback.php
- src/Term/TermList.php
- tests/unit/Snak/SnakListTest.php
In preparation for [T274821](https://phabricator.wikimedia.org/T274821)
> Update data-values to 3.0 and prepare for release

- .travis.yml
- composer.json
> Reflect the IRC migration to libera.chat
