wmde/WikibaseDataModel

src/Snak/SnakObject.php
tests/unit/Snak/PropertyNoValueSnakTest.php
tests/unit/Snak/PropertySomeValueSnakTest.php

Comparing with `self` is dangerous in an abstract base class because this compares the base class, not the sub classes. It's not a problem in this case because `getHash` contains the sub class name and is guaranteed to be different. But if we ever change `serialize` (as already discussed) `equals` may fail. Adding tests to make sure this never happens.
https://github.com/DataValues/DataValues/pull/12 does the same for the abstract `DataValueObject::equals`.

More robust Snak::equals

---

tests/unit/Entity/Diff/EntityDiffOldTest.php
tests/unit/Entity/Diff/ItemDiffTest.php

I'm not sure if this was required in an older PHPUnit version. But I'm sure it's not needed with our current PHPUnit version(s).

Drop static keywords from data providers

---

src/Term/AliasGroup.php
src/Term/AliasGroupFallback.php
src/Term/AliasGroupList.php
src/Term/Term.php
src/Term/TermFallback.php
src/Term/TermList.php

This is a re-submit of #334 since, apparently, having no documentation is better than having any.
Additional changes:
* Rearranged the setAliases code to avoid iterating the array twice.
* Inlined a few more trivial private setters.
* Dropped all `gettype` (introduced in #276) from the `Term` namespace since I find the added code complexity not worth it.

More descriptive Term/AliasGroupFallback docs

---

src/Term/AliasGroup.php
src/Term/AliasGroupFallback.php
src/Term/AliasGroupList.php
src/Term/Term.php
src/Term/TermFallback.php
src/Term/TermList.php
tests/unit/Term/AliasGroupFallbackTest.php
tests/unit/Term/AliasGroupListTest.php
tests/unit/Term/AliasGroupTest.php
tests/unit/Term/TermFallbackTest.php
tests/unit/Term/TermListTest.php
tests/unit/Term/TermTest.php

This depends on #335 (1st commit), please review the 2nd commit only.
Changes:
* All language codes are validated to be _non-empty_ strings now.
* Most of these exceptions had no test before.
* `AliasGroupList::hasGroupForLanguage` had no tests at all.

Empty string isn't a language code

---

RELEASE-NOTES.md
src/Entity/Item.php
tests/unit/Entity/ItemTest.php

This is a part of #290. I hope we can at least agree on that. The two parameters made optional by this patch are:
* `$statements` are already optional in `Property`, but not in `Item`, which is just a bit inconsistent.
* `$siteLinks` are specific for `Item`s.

Optional Item constructor parameters

---

src/Statement/Statement.php

This is a no-op change (it does not change any behavior and can be merged in any branch) split from #268 (a.k.a. #317) to make future patches easier to review.

Decrease inheritance in Statement

---

RELEASE-NOTES.md
src/ReferenceList.php
src/Statement/Statement.php
src/Statement/StatementList.php
tests/unit/Statement/StatementListTest.php

See https://gerrit.wikimedia.org/r/#/c/173828/.

StatementList constructor accepts Statement

---

RELEASE-NOTES.md
src/Entity/Diff/ItemDiffer.php
src/Entity/Item.php
tests/unit/Entity/Diff/EntityDiffOldTest.php
tests/unit/Entity/Diff/EntityDifferTest.php
tests/unit/Entity/Diff/EntityPatcherTest.php
tests/unit/Entity/Diff/ItemDiffTest.php
tests/unit/Entity/Diff/ItemDifferTest.php
tests/unit/Entity/Diff/ItemPatcherTest.php
tests/unit/Entity/Diff/PropertyPatcherTest.php
tests/unit/Entity/EntityTest.php
tests/unit/Entity/ItemTest.php
tests/unit/Entity/TestItems.php

Main reason to touch this was the `Item` constructor. The first parameter can be null but the others can not? This doesn't make much sense. Why not simply make them all optional?

Make all Item constructor parameters optional

---

RELEASE-NOTES.md
src/Term/Fingerprint.php

This is split from #290. I hope we all agree that the concept of an empty Fingerprint is in the scope of the DataModel.

Allow constructing empty Fingerprint

---

RELEASE-NOTES.md
src/Entity/Property.php
tests/unit/Entity/EntityTest.php
tests/unit/Entity/PropertyTest.php

Since the `Fingerprint` constructor parameter is now optional in `Item`, it should be optional in `Property` too.
This also adds tests for the `Property` constructor which was not tested at all, from what I can see.

Optional fingerprint constructor parameter in Property

---

src/Claim/ClaimList.php
src/SiteLinkList.php
src/Statement/StatementList.php
src/Term/AliasGroupList.php

As requested in https://github.com/wmde/WikibaseDataModel/pull/311#issuecomment-64713212.
Please note that `StatementList` always reindexed the array. It stopped doing this with #285 (released with 2.4.0).
I think this must be the responsibility of the `StatementList` class (as well as `ClaimList`, see the TODO) and not the calling code.

Clarify contracts of toArray methods

---

RELEASE-NOTES.md

* Main change is the `Property` line. The parameter is not "optional", it's required, but it can be `null` now.
* Changed two "the" to "all".
* All other lines are only re-orderd, but not changed.

Fix misleading Property release note

---

RELEASE-NOTES.md
src/Claim/Claim.php
src/Claim/ClaimGuid.php
src/SiteLink.php
tests/unit/SiteLinkTest.php

This also removes some of the `gettype` calls as reasoned in #335.

Disallow empty strings in SiteLink

---

src/Term/AliasGroup.php
src/Term/Term.php
tests/unit/Term/AliasGroupTest.php
tests/unit/Term/TermTest.php

Classes that do have subclasses need a slightly more complex equals implementation.
We *could* rework all equals methods like that but I do not think this is necessary or helpful. A straight instanceof is way more readable and sufficient in almost all cases.

Make Term::equals robust against subclasses

---

src/Entity/Entity.php
src/Entity/EntityDocument.php
tests/fixtures/EntityOfUnknownType.php

Pull request into 3.0.x-dev, not into master.
This fixes https://github.com/wmde/WikibaseDataModel/issues/310 and is the approach that came out of the discussion there. (We decided to not go with https://github.com/wmde/WikibaseDataModel/pull/312)
Note how we cannot use `EntityId` as PHP type hint, since then derivatives would not be able to do things such as accept an integer. This is needed since we support `$item->setId( 42 )`.
Also note that if we would just (doc) type hint against `EntityId`, we'd have a LSP violation. This is why the doc outlines a more detailed contract. (I'd rather avoid this situation here, since it can be avoided by not having the method, which is part of why I favoured the approach of deprecation. We have to do something though, and this approach seems benign …

Add setId to EntityDocument

---

RELEASE-NOTES.md
src/Entity/EntityIdValue.php

`Serializable::unserialize` isn't supposed to `@return` anything. Warning, this is a possible breaking change (in contrast to all other `unserialize` implementations in all other components, they never returned anything, but this one did).

Remove misleading return doc

---

src/Entity/EntityDocument.php

Main change here is: Remove the `@param` line. Note that the original `Entity` class did not had that either. It's misleading (subclasses don't fulfill this contract and aren't supposed to) and better described in text.

Remove misleading type from EntityDocument

---

src/Entity/Entity.php

At least PHPStorm does not like the `static` keyword, gets confused and does not know the actual return type any more. Which leads to "unknown method called" and other warnings. `self` does not have this problem.

Replace static with self

---

src/Statement/Statement.php
tests/unit/Statement/StatementTest.php

These methods are not used anyway.
This is split from #317 to make it easier to review. Documentation is missing here, it will be added later.

Drop unused Statement::getClaim and setClaim

---

src/Claim/ClaimListAccess.php
src/Claim/Claims.php
src/Entity/Entity.php
tests/unit/Claim/ClaimListAccessTest.php

Reverts wmde/WikibaseDataModel#363

Revert "Drop ClaimListAccess interface"

---

src/Entity/Item.php
src/Entity/Property.php
src/Statement/Statement.php
src/Statement/StatementList.php
tests/unit/ByPropertyIdArrayTest.php
tests/unit/Claim/ClaimStandaloneTest.php
tests/unit/Claim/ClaimsTest.php
tests/unit/Entity/Diff/EntityDiffTest.php
tests/unit/Entity/Diff/PropertyPatcherTest.php
tests/unit/Entity/ItemTest.php
tests/unit/Entity/PropertyTest.php
tests/unit/Statement/StatementListDifferTest.php
tests/unit/Statement/StatementListPatcherTest.php
tests/unit/Statement/StatementListTest.php
tests/unit/Statement/StatementTest.php

This patch does a single thing: Replace `( Claim $claim, ... )` with `( Snak $mainSnak, Snaks $qualifiers, ... )` in the `Statement` constructor (what I originally tried to submit as #268). This is split from #317 to make it easier to review.
Commit 1 is a separate pull request, see #367. Please merge #367 first.

Remove Claim from Statement constructor

---

src/HashArray.php
tests/unit/Snak/SnakListTest.php
tests/unit/Statement/StatementTest.php

Calling `new SnakList( $snak )` with a single snak object created an empty snak list. I added a specific test and immediately found that mistake in StatementTest. Whoops.

Fix HashArray accepting anything

---

tests/unit/Entity/DispatchingEntityIdParserTest.php

This is a pure refactoring change. It doesn't change any semantics.
This is split from #346 to make it much more focused.

Rename/refactor DispatchingEntityIdParserTest

---

composer.json

Remove "vendor/bin/" as suggested by @Krinkle in https://github.com/wmde/Diff/commit/acd15a05c6317c0a5a1ea446eca01123fce4bca1#commitcomment-9861167.
I'm also moving the `ci` command to the top.

Don't access vendor/bin in composer ci

---

src/Statement/Statement.php

This is split from #317 to make it easier to review. This introduces code duplication that is going to be removed in #317.
Note that I'm ordering the methods different here. This also avoids some mistakes still in #317, like calling the class a "claim".

Move implementations from Claim to Statement

---

src/Term/AliasGroup.php
src/Term/Term.php

This describes how the classes **should** be used. Note that the fallback subclasses violate this convention. Which is the reason why I want to add some documentation to the base classes.
The wording is similar to the one in https://github.com/DataValues/Time/pull/35.

More descriptive Term/AliasGroup docs

---

RELEASE-NOTES.md
src/ReferenceList.php
tests/unit/ReferenceListTest.php
tests/unit/Statement/StatementTest.php

Same as #356, but for the `ReferenceList` class.
This patch reduces the `HashableObjectStorage` base class dependency by not calling the parent constructor. I'm doing this on purpose to make it easier to possibly drop the base class some day.
This is split from #376 but submitted against master.
This fixes #371.

Fix ReferenceList accepting anything

---

src/Entity/EntityIdValue.php

`doubleval` is an alias in PHP. So is `double`. We use the word "double" for test doubles, for example, but never (except for this single place) as a type.

Favor float over alias double

---

tests/unit/ByPropertyIdArrayTest.php
tests/unit/ByPropertyIdGrouperTest.php
tests/unit/Claim/ClaimGuidTest.php
tests/unit/Claim/ClaimListAccessTest.php
tests/unit/Claim/ClaimTest.php
tests/unit/Entity/Diff/EntityDiffTest.php
tests/unit/Entity/Diff/ItemDiffTest.php
tests/unit/Entity/EntityTest.php
tests/unit/ReferenceListTest.php
tests/unit/ReferenceTest.php
tests/unit/Snak/SnakListTest.php

* Rename copy-pasted `$labelText` in description tests.
* Make existing docs more specific.
* Add some missing type hints.
* No empty line between `@dataProvider` and `@param`. Why? The params are what the provider provides, these two things are very strongly connected.
* No `@param` doc for "invalid" providers. Having docs that say `mixed` doesn't help. Some of the docs I'm removing in this patch were wrong.

Clean-up dataProvider docs and type hints

---

tests/unit/Entity/BasicEntityIdParserTest.php
tests/unit/Entity/DispatchingEntityIdParserTest.php

* The new `testCannotParseWithoutBuilders` is split from #346.
* `BasicEntityIdParserTest` did not had an "invalid" test.
* I changed the two "valid" providers to not rely on `getSerialization`.
* I changed the `@covers` tags so each test tests one class only. I hope this is ok. Lets see what Scrutinizer thinks about this patch.

Test coverage of {Basic|Dispatching}EntityIdParserTest

---

RELEASE-NOTES.md
src/Claim/Claims.php
tests/unit/Claim/ClaimsTest.php

Part of #157
* Claims::getHash is not used by any of our code as far as I can tell
* Claims::isEmpty is used by DataModel Serialization though that can easily be changed. I started updating that component to DM 3.x in https://github.com/wmde/WikibaseDataModelSerialization/pull/115

Remove more Claims methods

---

RELEASE-NOTES.md
src/ReferenceList.php
src/Statement/Statement.php
src/Statement/StatementList.php
tests/unit/ReferenceListTest.php
tests/unit/Statement/StatementTest.php

Reason for not using spaces in `,...`:
* Most common style across MediaWiki and our code base.
* It's less confusing for tools without a space.
~~I'm removing the "coding standards" tags because I don't see why they are needed and because these two places are the only places where we do this for variable argument functions. It's not a problem in all the other places, why is it here?~~
I re-purposed the patch and reworked the methods to either accept variable-length arguments or an array.

Unify variable function params docs

---

src/Statement/StatementList.php
tests/unit/Statement/StatementListTest.php

This is needed as replecament for Claims::indexOf, as per
https://github.com/wmde/WikibaseDataModel/issues/157

Add StatementList::indexOf

---

RELEASE-NOTES.md
src/Entity/Entity.php
tests/unit/Entity/EntityTest.php

This method is already unused, as far as I can see.

Drop deprecated entity::getAllSnaks

---

RELEASE-NOTES.md
src/Entity/Entity.php
src/Entity/Item.php
src/Entity/Property.php
tests/unit/Entity/EntityTest.php

This method is already unused, as far as I can tell. I can not find any occurrence of the word `hasClaims` in my local code base.

Drop deprecated Entity::hasClaims

---

tests/unit/Entity/Diff/EntityDiffTest.php
tests/unit/Statement/StatementListTest.php
tests/unit/Statement/StatementTest.php

* `Claim` is an alias for `Statement` now, both refer to the exact same class anyway.
* The compatibility test now compares each constant with itself.
* `testIsClaim` was a test to make sure `Statement` is a subclass or implements `Claim`. Now it's the other way around, `Claim` is an alias of `Statement`. There could be a test for this, but it does not belong to `StatementTest`.

Drop obsolete Claim related test code

---

src/Entity/Entity.php
src/Entity/Item.php
src/Entity/Property.php

`Claim` is an alias for `Statement` now. Therefor this is a no-op change that does not change any semantics.

Replace Claim alias with Statement

---

RELEASE-NOTES.md
src/Entity/Entity.php
src/Entity/Item.php
src/Entity/Property.php
tests/unit/Entity/ItemTest.php
tests/unit/Entity/PropertyTest.php

This method is already unused, as far as I can tell. I can not find any occurrence of the word `newClaim` in my local code base.

Drop deprecated Entity::newClaim

---

RELEASE-NOTES.md
src/Entity/Entity.php
src/Entity/Item.php
src/Entity/Property.php
tests/unit/Entity/ItemTest.php

This is part of #282. I prepared patches for the remaining usages of Entity::addClaim in the relevant components (mainly PropertySuggester and Wikibase.git).
Bug: [T78290](https://phabricator.wikimedia.org/T78290)

Drop deprecated Entity::addClaim

---

RELEASE-NOTES.md
src/Claim/Claims.php
tests/unit/Claim/ClaimsTest.php

This is part of #157. This is already unused in our code base.

Drop unused Claims::removeClaim

---

RELEASE-NOTES.md
src/Claim/Claims.php
tests/unit/Claim/ClaimsTest.php

As suggested in #157. This parameter is indeed not used in our code base. Adding an exception to make sure outdated code fails and does not silently do unexpected things.

Drop index parameter from Claims::addClaim

---

src/Claim/Claims.php

This is part of #157. This makes it easier to see the remaining usages of these methods. In some IDEs the class deprecation is not enough.

Deprecate all public methods in Claims

---

src/Reference.php
src/ReferenceList.php
tests/unit/ReferenceListTest.php
tests/unit/ReferenceTest.php

This is split from #416 but focuses on a single change: Calling the two constructors with `null` is not allowed any more.
Release notes will be updated later.

Do not allow null in Reference[List] constructors

---

RELEASE-NOTES.md
src/Claim/Claims.php
tests/unit/Claim/ClaimsTest.php

This is part of #157. There is a single usage of this method left in Wikibase.git, see https://gerrit.wikimedia.org/r/#/c/203795/.

Drop Claims::hasClaim

---

src/Claim/Claims.php
src/Entity/Diff/PropertyDiffer.php
src/Statement/StatementByGuidMap.php
src/Statement/StatementList.php
tests/unit/Entity/Diff/ItemDiffTest.php
tests/unit/Entity/EntityTest.php
tests/unit/Entity/ItemTest.php

This patch fixes a bunch of minor code smell issues, most reported by and found with PHPStorm.
* Remove unused use clauses.
* Add missing throws tags.

Fix minor code smell issues

---

src/Reference.php

This is currently not a problem because we do have a single class implementing the Snaks interface.
A simple workaround is to use `count()`, but I remember this caused big trouble somewhere else and we avoided it on purpose.

Not all Snaks implementations do have an isEmpty

---

src/Claim/ClaimGuidParser.php
tests/unit/Claim/ClaimGuidParserTest.php

As in PHPdoc the ClaimGuidParser::parse method
should return ClaimGuidParsingExceptions
This catchs previously uncaught EntityIdParsingExceptions
This relates to https://phabricator.wikimedia.org/T89100

Catch exception for invalid EntityId in GUID parser

---

src/Statement/StatementList.php

This very simple refactoring
* avoids looping arrays two times and
* skips type redundant checks.

Avoid looping Statement arrays twice

---

RELEASE-NOTES.md
src/Claim/Claims.php
src/Statement/StatementList.php
tests/unit/Statement/StatementListTest.php

This reverts #414 and #434.
Yes, we need a convenient method to get a Statement by GUID from a StatementList (or an array of Statements if multiple Statements do not have a GUID or do have the same GUID, which is currently possible).
But: a method that returns an integer index is not very useful. StatementList is not an ArrayObject and does not have a getter that accepts an integer index. The only way to make use of the index is via `toArray`, a guarantee that may change (see the discussion in #446) and is odd and dangerous.
```php
$array = $list->toArray();
$index = $list->getIndexByGuid( $guid );
$statement = $array[$index];
```
Such code looks suspicious to me. The two calls are unconnected. I'm accessing an array with an index returned by an other method? Are the two methods …

Replace StatementList::getIndexByGuid with getFirstStatementByGuid

---

src/Statement/StatementList.php

The idea of this method always has been that it is cheap and can be used to construct different statement collections or to get type hint support in loops
```php
foreach ( $statementList->toArray() as $statement ) { /* ... */ }
```
This means we cannot guarantee a non-spare array if we want to be able to add cheap removal methods (ie `removeStatement`).

Alter guarantees provided by StatementList::toArray

---

src/Statement/Statement.php
tests/unit/Statement/StatementTest.php

Both `ClaimList::addNewClaim` and `StatementList::addNewStatement` support an optional GUID parameter. These "new" methods should mirror the constructors. Everything else is just confusing. This is only one step to make them equal again, the other step is #268.

Add GUID to Statement constructor

---

tests/unit/Statement/StatementTest.php

As suggested in https://github.com/wmde/WikibaseDataModel/pull/306#discussion_r29303219.

Rework invalid GUID tests

---

RELEASE-NOTES.md
src/Entity/Property.php

The last 2 remaining uses of this method I could find (in my local code base, please double check) are removed in:
* https://gerrit.wikimedia.org/r/#/c/201428/
* https://github.com/wmde/WikibaseQuery/pull/61

Drop long deprecated Property::newEmpty

---

src/Statement/StatementByGuidMap.php
tests/unit/Statement/StatementByGuidMapTest.php

Per https://phabricator.wikimedia.org/T98180 &ndash; please only comment on the issue and not on this pull request (unless there are actual mistakes in this PR).

Rename getStatementByGuid to getStatementWithGuid

---

RELEASE-NOTES.md
src/Statement/StatementList.php
tests/unit/Statement/StatementListTest.php

As @thiemowmde [has pointed out correctly](https://phabricator.wikimedia.org/T98143#anchor-1265330), `StatementList::removeStatementsWithGuid` alone does not suffice all our needs. We also want to have a method to set a whole list of statements to the `StatementList`.
This patch just takes code from the constructor and makes it a publicly available method, so that everyone dealing with a `StatementList` no has full access and can also set the whole list. This is especially useful for classes like `ByPropertyIdGrouper` or (proposed) `ByPropertyIdMap` which return a list of statements that can be passed to this method directly.

Add setStatements to StatementList

---

Aliases.php
RELEASE-NOTES.md
WikibaseDataModel.php
src/Entity/Item.php
src/Entity/Property.php
src/Statement/StatementListProvider.php
tests/component/AutoloadingAliasesTest.php

When having `FingerprintProvider` in the Term namespace, `StatementListProvider` should also be in the Statement namespace.
Furthermore, this makes the src/ folder less crowded.

Move StatementListProvider into the Statement namespace

---

src/Statement/StatementList.php
tests/unit/Statement/StatementListTest.php

@JeroenDeDauw Addresses your comment and adds tests for those cases.
*Edit:* Added a missing `@since 3.0` tag as well.

Dont modifiy StatementList when invalid arguments passed to setStatements

---

RELEASE-NOTES.md

I don't know who introduced the brackets, but everywhere else, we use "Removed `bla`, use `blubb` instead" so this should be done here as well.

Same format of alternatives in release notes

---

Aliases.php
tests/unit/Entity/PropertyTest.php

I may confuse something here but I think this is an actual bug.
The test is unrelated, just a mismatch I found, obviously caused by replacing `new EntityId` with `new PropertyId` without renaming the test.

StatementListProvider is not a class

---

RELEASE-NOTES.md
src/Entity/Item.php
src/Entity/Property.php
src/Statement/StatementList.php
src/Statement/StatementListHolder.php
tests/unit/Statement/StatementListTest.php

This reverts #481 and #483 per argument given in https://github.com/wmde/WikibaseDataModel/pull/481#issuecomment-101665472 and replaces it with an interface that solves the issue that motivated the addition of the method.
This fixes #485.
[Bug: T75496](https://phabricator.wikimedia.org/T75496)

Add StatementListHolder

---

src/Statement/StatementByGuidMap.php
src/Statement/StatementList.php
tests/unit/Statement/StatementByGuidMapTest.php

Existing "byId" methods:
* `ByPropertyIdArray::getByPropertyId`
* `ByPropertyIdGrouper::getByPropertyId`
* `SiteLinkList::getBySiteId`
Existing "withId" methods:
* `SiteLinkList::hasLinkWithSiteId`
* `SiteLinkList::removeLinkWithSiteId`
* `StatementByGuidMap::hasStatementWithGuid`
* `StatementByGuidMap::getStatementWithGuid`
* `StatementByGuidMap::removeStatementWithGuid`
* `StatementList::removeStatementsWithGuid`
* `StatementList::getWithPropertyId`
* `StatementList::getFirstStatementWithGuid`
* 3 more in the deprecated `Claims`
Suggested naming scheme:
* The object type should not be repeated if a method returns an instance of `self`, e.g. not ~~`Foo::getFooByBar`~~ but `Foo::getByBar`.
* "has*Object*With" and "remove*Object*With" no matter if the parameter is an unique identifier or …

Partial revert of the With vs. By inconsistency

---

src/Statement/StatementList.php
tests/unit/Statement/StatementListTest.php

Reverts #459. I don't understand why #459 was commited and merged without referencing the not finished discussion in #446.

Revert "Alter guarantees provided by StatementList::toArray"

---

RELEASE-NOTES.md
src/Statement/StatementList.php
tests/unit/Statement/StatementListTest.php

For parity with
* `ByPropertyIdArray::getByPropertyId`
* `ByPropertyIdGrouper::getByPropertyId`
and for the reasons outlined in https://github.com/wmde/WikibaseDataModel/pull/487#issue-75975410.
[Bug: T98180](https://phabricator.wikimedia.org/T98180)

Rename getWithPropertyId to getByPropertyId

---

RELEASE-NOTES.md
src/Statement/StatementList.php
tests/unit/Statement/StatementListTest.php

As requested by @Benestar in https://phabricator.wikimedia.org/T98180#1283186 and for the reasons outlined in https://github.com/wmde/WikibaseDataModel/pull/487#issue-75975410.
Not a big deal, the method is used only a single time in `SnaksFinder` in Wikibase.git.
[Bug: T98180](https://phabricator.wikimedia.org/T98180)

Rename getWithRank to getByRank

---

RELEASE-NOTES.md
src/Entity/Item.php
src/Entity/Property.php

Right now code as follows is deprecated:
```php
$item = new Item();
$item->setLabel( 'en', 'foo' );
$item->setDescription( 'de', 'bar' );
```
This is caused by these setters being deprecated in Entity, which
was done to deprecate code assuming all entities have these terms,
and to discourage bad interface segregation. The above code suffers
from neither these problems, and is a style often used in tests,
and has no clean alternative due to PHPs lack of named parameters.
Hence this undeprecation in Item and Property, keeping the one in
Entity.

Undeprecate term setters in Item and Property

---

RELEASE-NOTES.md
src/Entity/Entity.php
tests/unit/Entity/ItemIdSetTest.php

I realized this in https://github.com/wmde/WikibaseDataModel/pull/492#discussion_r31474648.
~~I consider this a mistake that's not worth any documentation.~~ I did a quick check in our code base and could not find a user relying on these return values.
The renamed method is unrelated, I just found this setter that's not a setter while searching for setters that may return something.

Do not return anything from Entity setters

---

src/ReferenceList.php
src/Statement/Statement.php
tests/unit/ReferenceListTest.php

Instead, it now implements some new interfaces like
Countable and IteratorAggregate.
Internally, the class uses an array to store references.
It is now no longer possible to add non-Reference objects
to a ReferenceList. Modifications are only possible through
the provided methods in the class itself.
The full diff can be found here: https://github.com/wmde/WikibaseDataModel/compare/remove-splobjectstorage-inheritance
Depends on #501

Make ReferenceList no longer extend SplObjectStorage 

---

src/ReferenceList.php
src/Statement/Statement.php
tests/unit/ReferenceListTest.php

Methods which were never used in our code base or have an easy replacement got removed
See #499 for an earlier version of this PR (against the wrong base)
Depends on #498

Remove unused methods from ReferenceList

---

tests/unit/ByPropertyIdArrayTest.php
tests/unit/Claim/ClaimsTest.php

This patch removes/replaces all remaining usages of `Claim`, which is now an alias.

Replace Claim alias usages

---

src/Entity/Entity.php

This is an alternative "resubmission" of #512. Technically the additional deprecation tags are not needed because the class is already deprecated. But the individual tags make the deprecation much more obvious in IDEs, because the methods are highlighted as deprecated. They are not without these tags.
[Bug: T98290](https://phabricator.wikimedia.org/T98290)

Add deprecated tags to all Entity methods

---

RELEASE-NOTES.md
src/Entity/Entity.php
tests/unit/Entity/EntityTest.php
tests/unit/Entity/ItemTest.php

Not used in Wikibase.git anymore, some usages in Wikibase DataModel Services left, which I'm going to remove as well.

Remove Entity::copy

---

src/Snak/DerivedPropertyValueSnak.php
tests/unit/Snak/DerivedPropertyValueSnakTest.php

This allows using the short constructor in tests etc.

Make constructor signature of DerivedPropertyValueSnak match parent

---

src/Entity/Entity.php

These methods can be safely removed as they are reimplemented in all subclasses

Remove methods from Entity undeprecated in subclasses

---

RELEASE-NOTES.md
src/Term/AliasesProvider.php
src/Term/DescriptionsProvider.php
src/Term/Fingerprint.php
src/Term/LabelsProvider.php

The method names currently conflict with the ones defined in `Entity`. <s>We should consider renaming them to `getLabelList`, `getDescriptionList` and `getAliasList` and rename them again in the next breaking release (4.0).</s>

Introduce provider interfaces for labels, descriptions and aliases

---

RELEASE-NOTES.md
src/Entity/Entity.php
src/Term/FingerprintHolder.php

This interface is the same as `StatementListHolder` for `StatementListProvider`. We might also consider to add the setter to `FingerprintProvider` itself but I guess the same argumentation as for `StatementListHolder` will happen and we should stay consistent here.

Add FingerprintHolder interface

---

src/Entity/Entity.php

While Entity is deprecated, usage of this method is not.
This is entirely valid, yet is now seen as deprecated:
```php
$item = new Item();
$item->copy();
```

Remove misleading deprecation tag

---

RELEASE-NOTES.md
src/Entity/Entity.php
src/Term/FingerprintHolder.php

#531 should be merged first
Reason for not waiting longer with the release is that now we switched to WB DM 4.0 in Wikibase.git, we have tons of incorrect deprecation noticed there, which is fixed by #531 and several already merged commits.

4.1.0 release

---

src/Claim/Claims.php

In production Claim is an alias, so there is no real difference between Claim and Statement. But the IDE and certain tools think Claim is a subclass of Statement because of Aliases.php. All code using the deprecated Claims class calls it with Statement objects, not with Claim objects. The tools think we are passing a superclass when only a subclass is allowed.
This is the most minimal fix to avoid these warnings.

Stop using the Claim alias

---

src/Claim/Claims.php

I did a fulltext search for `Statement $claim`. See https://gerrit.wikimedia.org/r/#/c/231249/ for the same patch in the Wikibase.git master.

Avoid calling Statement's $claim

---

tests/unit/Entity/EntityTest.php
tests/unit/Entity/ItemTest.php
tests/unit/Entity/PropertyTest.php

This reverts parts of https://gerrit.wikimedia.org/r/#/c/222978/. See https://github.com/wmde/WikibaseDataModel/pull/531 for arguments. In short: Yes, `Entity` is deprecated and calls to `Entity::copy` should not be called. But `Item::copy` and `Property::copy` are **not** deprecated.

Revert to use non-deprecated Item::copy and Property::copy

---

src/Entity/ItemIdSet.php
src/Statement/StatementByGuidMap.php
src/Statement/StatementList.php
src/Term/AliasGroupList.php
src/Term/TermList.php

Note that we already did this in https://github.com/wmde/WikibaseDataModel/blob/master/src/SiteLinkList.php#L102. The "perfect" type hint would be `Traversable<ItemId>`, but PHP does not support this and IDEs don't understand it and get confused. The combination of `Traversable|ItemId[]` is a workaround to help IDEs understand what type the elements in a foreach loop are.

Add workaround type hints to getIterator implementations

---

.travis.yml

See http://docs.travis-ci.com/user/caching/
> The cache’s purpose is to make installing language-specific dependencies easy and fast, so everything related to tools like Bundler, pip, Composer, npm, Gradle, Maven, is what should go into the cache.

Use the composer cache

---

.travis.yml

They are faster, esp now we are using the cache. Originally we switched to clones since the tarballs failed sometimes, though this should already be mitigated by us now using `travis_retry`

Use tarballs rather than clones

---

RELEASE-NOTES.md
WikibaseDataModel.php
composer.json
src/Entity/ItemIdParser.php
tests/unit/Entity/ItemIdParserTest.php

See the description in the new class: https://github.com/wmde/WikibaseDataModel/pull/503/files#diff-6f98701bbb711986fc9b49f2c8c8238cR8
[Bug: T102840](http://phabricator.wikimedia.org/T102840)

Add ItemIdParser

---

tests/unit/ByPropertyIdArrayTest.php
tests/unit/Statement/StatementListTest.php

These are the only remaining usages of the Claims class (besides `Item::setClaims` and `Property::setClaims`). I'm aware that these classes are also touched in other patches. The difference is that this patch here is non-breaking. I will rebase the other patches when this is merged.
[Bug: T78281](https://phabricator.wikimedia.org/T78281)

Replace Claims with ArrayObject in tests

---

src/ReferenceList.php
tests/unit/ReferenceListTest.php

Motivated by https://gerrit.wikimedia.org/r/#/c/242084/1/view/src/ClaimHtmlGenerator.php.
The second test with the iterator stuff is because an other valid implementation of an isEmpty method could use `!$this->valid()` (this is done in the HashArray class) but would reset the iterator.

Add ReferenceList::isEmpty

---

tests/unit/ReferenceListTest.php

I can not find a test that checks if a ReferenceList can be constructed from an other Traversable object.

Add test to construct ReferenceList from ReferenceList

---

phpcs.xml

This is not the MediaWiki rule set, right?
This is split from #565.

Rename PHPCS rule set to WikibaseDataModel

---

src/ByPropertyIdArray.php
src/Entity/Entity.php
src/Entity/EntityId.php
src/Entity/EntityIdParsingException.php
src/Entity/EntityIdValue.php
src/Entity/Item.php
src/Entity/Property.php
src/HashArray.php
src/HashableObjectStorage.php
src/Reference.php
src/Snak/SnakObject.php
src/Statement/StatementGuid.php
tests/fixtures/HashableObject.php
tests/unit/Internal/MapValueHasherTest.php
tests/unit/Statement/StatementByGuidMapTest.php
tests/unit/Statement/StatementListTest.php

This patch was motivated by the removal of the last remaining full qualified class names. In addition, I included a few minor code style clean ups:
* Avoid the alias `is_integer`.
* Prefer `!( $var instanceof Class )` with brackets.
* Split long lines.

Avoid full qualified class names

---

phpmd.xml
src/HashArray.php
src/ReferenceList.php

I strongly believe that such tags are a code smell that's worse than the benefit of the partly suppressed check. If the TooManyPublicMethods count is to high, either increase it or add exclude-pattern lines to the phpmd.xml file.

Remove all @SuppressWarnings tags

---

tests/unit/Entity/ItemIdTest.php
tests/unit/Entity/PropertyIdTest.php

I find it odd that this method can be misused to inject unsupported stuff into the object. But I do not think this is relevant. As far as I know we are not using this code in production.
I'm adding tests to make this behaviour more obvious. If you think this should be fixed somehow, please tell me, and I will create an other patch. However, please merge this patch as it is because this here does not count as a change, while an actual fix will be a breaking change.

More tests for ItemId/PropertyId::unserialize

---

tests/unit/Snak/SnakListTest.php

This is split from #439. This tests the current behavior of the class and makes sure we do not do breaking changes without noticing.

Add more edge case tests for SnakList construction

---

WikibaseDataModel.php

it's still useful for users of the component.

Re-add php version constant

---

src/ReferenceList.php
tests/unit/ReferenceListTest.php

There is no single usage of this method in our whole code base.
Furthermore, if no duplicates should be allowed, a different data
structure should be used.

Get rid of unused removeDuplicates method

---

src/ReferenceList.php
tests/unit/ReferenceListTest.php

This removes the inheritance between ReferenceList and SplObjectStorage
and replaces it with a native array. To make the change as minimal as
possible, the Countable interface and the IteratorAggregate interface are
now implemented by ReferenceList so that it can be used almost the same as
before (like iterating over it and calling count() on it).

Refactor ReferenceList

---

RELEASE-NOTES.md
src/Entity/Entity.php
src/Entity/EntityDocument.php
src/Entity/Item.php
src/Entity/Property.php

This method is needed in EntityDocument to be able to compare two entities
where their type is not known. Entity now also doesn't implement
Comparable anymore.
The signature of the equals method has changed from mixed param type to
typehinting against EntityDocument.

Add equals to EntityDocument

---

RELEASE-NOTES.md
src/Entity/EntityDocument.php
tests/unit/ReferenceListTest.php

This is split from #621:
* This adds a few more regression tests.
* This rearranges the release notes. The only substantial change is that I removed the "still implements" line.

Add more regression tests for ReferenceList

---

RELEASE-NOTES.md
src/Entity/EntityDocument.php
src/Entity/Item.php
src/Entity/Property.php

This mostly reverts the unnecessary breaking changes in #615. The title of that pull request was "Add equals to EntityDocument", and this is mostly what this patch now does, when you compare the code with the previous 4.4 release: The `Comparable` interface moves from the deprecated abstract base class `Entity` up to the `EntityDocument` interface. That's all.
This patch also cleans up the release notes (extensively updated in 2df96fa988c199ebec318f55150f1b22dd3eedf6, thanks a lot for that, @Benestar) and adds some missing regression tests (I tried and these tests run with 4.4).

Revert unnecessary breaking change to Item::equals

---

src/Entity/EntityDocument.php

We may not need this at all when we make use of the `clone` keyword and PHP's magic `__clone` methods instead, see http://php.net/manual/en/language.oop5.cloning.php. I will upload a separate patch for this alternative proposal.

Add EntityDocument::copy

---

src/ReferenceList.php
tests/unit/ReferenceListTest.php

The braking change to the indexOf method was introduced in #609 and reverted in #617. The test was added in #617 but did not mentioned what it is testing: identity vs. equality.

Rework test for ReferenceList::indexOf using identity

---

src/Entity/EntityDocument.php

The only substantial change in this patch is the added `@since 5.0` and the use of `self`.
I'm also removing newlines to make use of the common 100 character line length limit, and rearranging the methods:
1. Type.
2. Id getter and setter.
3. isEmpty and equals.

Add missing since tag to EntityDocument

---

src/Entity/Item.php
src/Entity/Property.php

This acts as a baseline for a whole bunch of patches that all touch the same code, including #626, #630, #631 and #632. All these patches should become a bit easier to review with this baseline.
The `@since` tags are intentional, because both classes are guaranteed to have a `copy` method since 0.1

Copy copy methods to Item and Property

---

src/Entity/EntityIdValue.php
src/Entity/ItemId.php
src/Entity/PropertyId.php
src/HashArray.php
src/ReferenceList.php

Follow up to  #597.
Originally, this patch changed `ItemId::unserialize` and `PropertyId::unserialize` to throw exceptions and call the constructor. But I was not sure if …
1. … this is relevant in production. As far as I can tell this is unused.
2. … this should not be done because these methods should be as fast as possible and not do any checks.
I reworked this patch completely because I realized these `unserialize` methods are not intended to be called manually. The should only be called internally when using PHP's `unserialize( $string )`. This should be as fast as possible.

Simplify ReferenceList::unserialize

---

phpcs.xml

The changes in this patch are for ease and consistency in the phpcs.xml file, but do not change the actual rules.
* Remove not needed "absolute" lines. These lines do not add anything because we are reporting warnings as errors anyway.
* Swap the two metrics rules so they are in alphabetic order.
* Use exclude instead of setting severity to 0. See https://gerrit.wikimedia.org/r/260731 for an explanation.

Cleanup phpcs.xml file

---

src/ReferenceList.php
tests/unit/ReferenceListTest.php

I'm actually very confused by this because as far as I can see the old implementation of this only removed the first reference with that hash in the list. [[1]](https://github.com/wmde/WikibaseDataModel/blob/4.4.0/src/ReferenceList.php#L192) However, without this patch, tests in Wikibase are broken because of this missing feature. [[2]](https://integration.wikimedia.org/ci/job/mwext-Wikibase-repo-tests-sqlite-hhvm/8473/consoleFull)
Anyways, it is very bad to change the array keys while iterating over it in a for loop so we need to fix that to use it in Wikibase and release a 5.0.1.

Fix ReferenceList not removing all reference with same hash

---

tests/unit/ReferenceListTest.php

Can you imagine what the `$this->assertTrue( true )` and the lines above was meant to do? I tracked it down to commit c721869f41fa0637a7171a61526b34acfaee4101 (on Gerrit). To me it appears to be a mistake.

Remove dead code from ReferenceListTest

---

src/ReferenceList.php
tests/unit/ReferenceListTest.php

~~This is really ugly performance-wise, and we should think about this twice before merging it.~~ Reworked to use `spl_object_hash()` to replicate the behavior of the previous, SPL object store based implementation.
Marked as a bug because it is a regression between 4.4.0 (the tests in this patch succeed with 4.4.0) and 5.0.0.

Fix regression when adding the same reference object twice

---

RELEASE-NOTES.md
src/Entity/Entity.php
src/Entity/EntityDocument.php
src/Entity/Item.php
src/Entity/Property.php
src/Statement/Statement.php
src/Statement/StatementList.php
src/Term/Fingerprint.php
tests/unit/Entity/ItemTest.php
tests/unit/Entity/PropertyTest.php

Alternative to #625. Personally I prefer this one. It's the native PHP way of copying/(deep)cloning objects.
I'm not totally happy with the test because it's so long.

Implement __clone to fully support deep cloning

---

src/Term/AliasGroupList.php
src/Term/TermList.php
tests/unit/Term/AliasGroupListTest.php
tests/unit/Term/TermListTest.php

This is about performance.
Why do I think these checks are not necessary? Because nothing unexpected happens when an array key is not found.
* When you provide an integer key or something else that can't be found in the array, all three methods have a well defined, expected behavior. These methods are not supposed to check if an array key is allowed to be in the array, this must be checked in the constructor/setter.
* On the other hand, when you provide some object that's then casted to string, and this string is then found in the array, why shouldn't that work?

Remove type checks from AliasGroup/TermList getters

---

RELEASE-NOTES.md
src/Entity/Item.php
src/Entity/Property.php
tests/unit/Entity/ItemTest.php
tests/unit/Entity/PropertyTest.php

With this patch applied, Item and Property implement the term related
interfaces LabelsProvider, DescriptionsProvider and AliasesProvider.
Note that the signature of getLabels and getDescriptions changed and those
methods now return TermList objects instead of plain arrays.
Depends on #631 
**Note that this shouldn't be merged before we are sure the next release will be 6.0.0**
Bug: [T126152](https://phabricator.wikimedia.org/T126152)

Add interfaces to Item and Property

---

tests/unit/ReferenceListTest.php

I wrote this test in 4.4.0. It describes the behavior of version 4.4.0 and succeeds there. It failed in 5.0.1. It succeeds in 5.0.2.
The test does test multiple things:
* It checks if identical objects are ignored. This was broken in 5.0.1 and got fixed in 5.0.2 by #639.
* It checks if it's possible to move an existing reference to a lower index.
* It tries to move a reference to a higher index, but expects this to fail, because 4.x was not able to do this.

Test 4.x behavior of ReferenceList::addReference at index

---

src/Entity/Item.php
src/Entity/Property.php
tests/unit/Entity/ItemTest.php
tests/unit/Entity/PropertyTest.php

New instances should be created instead of clearing an existing Entity.
The only real usecase for this seems to be the clear=true parameter in the
wbeditentity api module.
Property::clear even had a bug in that it didn't clear the statements but
only the fingerprint.

Remove clear from Entity, Item and Property

---

src/Statement/StatementList.php
tests/unit/Statement/StatementListTest.php

I'm proposing this as the most simple fix to get rid of StatementListHolder. This is currently not possible because there is no way to re-implement the index feature in ChangeOpStatement without having an `Entity::setStatements` or at least `StatementList:clean` method.
* Currently, ChangeOpStatement turns the StatementList into an array, does all the index stuff, recreates a new StatementList and calls setStatements. Main issue: We decided we want to get rid of this setter together with all "holder" interfaces. This now turned into a pressing issue because we do not want MediaInfo to implement the deprecated holder interface.
* ChangeOpStatement could, in theory, clean the StatementList (either with a `clear` method we do not want for good reasons, see #649, or by calling the existing …

Add index parameter to StatementList::addStatement

---

src/Entity/EntityIdValue.php
tests/unit/Entity/EntityIdValueTest.php

Alternative for #669, with a very important difference: With this patch EntityIdvalue::newFromArray becomes a legacy thing that could be deprecated or even removed. It ~~can~~ should not be used for deserialization any more. It can not be used any more the moment we drop the two legacy keys "entity-type" and "numeric-id". Most importantly: It will never support new entity types. This will be done by https://github.com/DataValues/Serialization/pull/14.
The assumption that getArrayValue and newFromArray roundtrip is not true any more with this patch. I'm not sure if this makes this a breaking change.
I wanted separate pull requests so you can see the difference.
[Bug: T132592](https://phabricator.wikimedia.org/T132592)

Serialize EntityIdValue with "id" without newFromArray support

---

src/ByPropertyIdArray.php
tests/unit/ByPropertyIdArrayTest.php

I keep running into this problem. When you pass a StatementList to this class, which is what it is build for, it iterates the **properties** of the StatementList object, not the statements.
I'm aware this is deprecated and should die entirely. That's why I'm going for the most simple fix I can think of.

Block ByPropertyIdArray construction from object properties

---

src/Entity/Int32EntityId.php
src/Entity/ItemId.php
src/Entity/PropertyId.php
tests/unit/Entity/EntityIdTest.php
tests/unit/Entity/EntityIdValueTest.php
tests/unit/Entity/ItemIdTest.php
tests/unit/Entity/PropertyIdTest.php

Alternative proposal for [T135650](https://phabricator.wikimedia.org/T135650). The main difference to #667 is that this here is a breaking change while #667 is not. #667 will require consumers to do the int32 check, while this patch requires the same int32 check on construction time.
[Bug: T135650](https://phabricator.wikimedia.org/T135650)

Add Int32EntityId

---

src/Statement/ReferencedStatementFilter.php
tests/unit/ReferenceListTest.php

I was doing a global search for older code that counts references, because we introduced the isEmpty method a while ago.

Avoid counting when not necesarry

---

src/Entity/EntityId.php
src/Entity/ItemId.php
src/Entity/PropertyId.php
tests/unit/Entity/EntityIdTest.php
tests/unit/Entity/ItemIdTest.php
tests/unit/Entity/PropertyIdTest.php

Task on Phabricator: https://phabricator.wikimedia.org/T145516

Support foreign EntityIds.

---

tests/unit/ByPropertyIdArrayTest.php
tests/unit/Entity/EntityIdTest.php
tests/unit/Entity/EntityIdValueTest.php
tests/unit/Entity/ItemIdTest.php
tests/unit/Entity/ItemTest.php
tests/unit/Entity/PropertyIdTest.php
tests/unit/Entity/PropertyTest.php
tests/unit/Statement/StatementGuidTest.php

Multiple arguments to remove these:
* It's easy to run a single …Test.php file or a single directory of tests. These `@group` tags are not needed to do this.
* What these tags do is, in essence, repeating either the class or the directory name. We tend to forget this when renaming or moving files. A good amount is already outdated.
* Some of these `@group` tags are the result of copy pasting and do not belong to the file they are in.

Remove "@group …Test" tags for individual tests

---

src/Entity/DispatchingEntityIdParser.php
tests/unit/Entity/DispatchingEntityIdParserTest.php

~~This includes code from https://github.com/wmde/WikibaseDataModel/pull/678 and should only be merged after `EntityId` handles foreign IDs.~~

Add support for repo prefixes in DispatchingEntityIdParser

---

src/Entity/EntityId.php

https://github.com/wmde/WikibaseDataModel/pull/678 re-added the constructor so the note is no longer valid.
Or should this note rather be kept and a new one added saying "Constructor public since 6.2"?

Remove no longer valid note in EntityId docs

---

composer.json
src/Assert/RepositoryNameAssert.php
tests/unit/Assert/RepositoryNameAssertTest.php

This is re-submission of https://github.com/wmde/WikibaseDataModelServices/pull/155, as it has been suggested it better fits in here.
Background (repeated): similar checks are done in https://github.com/wmde/WikibaseDataModelServices/pull/150,  https://github.com/wmde/WikibaseDataModelServices/pull/150, https://gerrit.wikimedia.org/r/#/c/314682/, https://github.com/wmde/WikibaseDataModelServices/pull/146, https://github.com/wmde/WikibaseDataModelServices/pull/149. It makes sense to have dedicated function(s) for such things. and not duplicate validation code. It would also make it easier to only have to adjust validation code in one place if there are more restrictions added on repository names etc.
Few little things changed here compared to …

Add functions to assert a value is a valid repository name, or an array indexed by valid repository names

---

docs/foreign-entity-ids.wiki

As we already switched to short array syntax in this repository in https://github.com/wmde/WikibaseDataModel/pull/683

Use short array syntax in docs for consistency

---

src/Entity/ItemId.php
src/Entity/PropertyId.php
tests/unit/Entity/ItemIdTest.php
tests/unit/Entity/PropertyIdTest.php

It seems that disallowing calling getNumericId on foreign ItemId
and PropertyId instances (ie. containing a prefix in their serializations)
was not right.
Although it definitely it should not be assumed that "Q1" and "foo:Q1"
refer to the same entity of type "item" and numeric part of id "1",
the actual code accessing data from the database (ie. accessing
numeric values from the DB) must make use of getNumericId to get
the numeric part of both "Q1" and "foo:Q1".
It should be the responsibility of the caller to make sure the
right database is accessed and that the number part of id makes
sense in the given context. ItemId/PropertyId should not really
know anything about this.

Allow calling getNumericId on foreign ItemIds and PropertyIds

---

RELEASE-NOTES.md

https://github.com/wmde/WikibaseDataModel/pull/696 submitted against a better named branch.
Note this is not pull request onto master!
https://github.com/wmde/WikibaseDataModel/pull/695 (https://github.com/wmde/WikibaseDataModel/pull/695/commits/00d2df05a79c6f7b83d74bb12dc7c69eb9820f3a) introduced a bug fix we would like to release as version 6.3.1.
As master is already preparing for the breaking release 7.0.0 I've created a branch https://github.com/wmde/WikibaseDataModel/tree/release631 which is the master as of 6.3.0, onto which I've cherry picked https://github.com/wmde/WikibaseDataModel/pull/677/commits/5344646f42b349a148c00c17114d10cd1e9f0c56 (not necessarily needed but added to have the same docs as master has; I might remove it if preferred), and the actual bug fix …

Release notes 6.3.1

---

composer.json

Recent versions of PHPUnit deprecated some stuff
that we can't get rid off since that would mean
using new stuff only available in versions of PHPUnit
that do not support PHP 5.5.
Yay for supporting legacy PHP /o\

Avoid PHPUnit deprecation warnings

---

src/Entity/DispatchingEntityIdParser.php
src/Entity/ItemIdParser.php

Forwarding the original exception can be very helpful when debugging.

Add missing parameters to EntityIdParsingException

---

src/ReferenceList.php
tests/unit/ReferenceListTest.php

These two additions (a new test case for inserting a reference between two existing ones, and the exception) solve two of the three mutation testing issues reported in https://github.com/wmde/WikibaseDataModel/pull/654#issuecomment-270764683.
The remaining issue (where `>=` was mutated into `>`) is a trivial performance optimization. Both code paths (straight appending and inserting at the top most position) are supposed to produce the same output.

Add missing ReferenceList::addReference test case

---

src/HashArray.php
tests/unit/HashArray/HashArrayWithDuplicatesTest.php
tests/unit/HashArray/HashArrayWithoutDuplicatesTest.php

This is split from #702 to make it easier to review.

Remove unused HashArray::rebuildIndices and indicesAreUpToDate

---

src/HashArray.php
tests/unit/HashArray/HashArrayTest.php
tests/unit/HashArray/HashArrayWithDuplicatesTest.php
tests/unit/HashArray/HashArrayWithoutDuplicatesTest.php

This is split from #702 to make it easier to review.
Note that we already removed ReferenceList::removeDuplicates in 5.0.
The two testHasElement and testRemoveElement tests are moved without touching them, because they are not applicable to a test setup with duplicates.

Drop unused HashArray::removeDuplicates

---

src/Entity/EntityIdValue.php
src/Entity/ItemId.php
src/Entity/PropertyId.php
tests/unit/Entity/EntityIdTest.php
tests/unit/Entity/EntityIdValueTest.php
tests/unit/Entity/ItemIdTest.php
tests/unit/Entity/PropertyIdTest.php

This is an alternative draft for #716. Pinging @brightbyte and @JeroenDeDauw.
This patch does 2 things:
1. Change EntityIdValue::serialize to use the native `serialize` instead of JSON.
2. Simplify both ItemId and PropertyId serializations to the straight string.
The 1st change makes the serialized string much longer, the 2nd change minimizes it again.
In all cases I keep compatibility with the previous serialization formats.

Rework native EntityId(Value) serializations

---

phpcs.xml
src/Snak/PropertyValueSnak.php
src/Snak/SnakObject.php
tests/unit/ReferenceListTest.php
tests/unit/Snak/DerivedPropertyValueSnakTest.php
tests/unit/Snak/PropertyNoValueSnakTest.php
tests/unit/Snak/PropertySomeValueSnakTest.php
tests/unit/Snak/PropertyValueSnakTest.php

This changes Snak serialization to use the full string representation of property IDs.
NOTE: serialize/unserialize is used mainly when cloning Statements.
NOTE: it's unclear if this completely fixes T157442
NOTE: this changes snak hashes, and consequently reference hashes! This may break reference update/removal!
[Bug: T157442](https://phabricator.wikimedia.org/T157442)

Don't use numeric IDs for internal PHP serialization.

---

src/HashArray.php
src/PropertyIdProvider.php
src/Statement/Statement.php

This goes along with https://gerrit.wikimedia.org/r/339131.

Remove non-informative "getFoo returns foo" comments

---

src/Entity/ItemId.php
src/Entity/PropertyId.php
tests/unit/Entity/ItemIdTest.php
tests/unit/Entity/PropertyIdTest.php

A convenience method that allows us to avoid constructing ugly code (see https://gerrit.wikimedia.org/r/337806).

Add ItemId and PropertyId::newFromRepositoryAndNumber

---

RELEASE-NOTES.md
src/Statement/StatementList.php
src/Term/AliasGroupList.php
src/Term/TermList.php
tests/unit/Statement/StatementListTest.php
tests/unit/Term/AliasGroupListTest.php
tests/unit/Term/TermListTest.php

This is needed as a replacement for users of the holder interfaces to remove all elements from one of the given list classes.
[Bug: T128363](https://phabricator.wikimedia.org/T128363)

Add clear to list classes

---

src/Snak/SnakList.php
tests/unit/HashArray/HashArrayTest.php
tests/unit/Snak/SnakListTest.php

This introduces a constructor to the SnakList class that does not call the parent constructor. This is done on purpose to decrease the inheritance and possibly get rid of the `ArrayObject` dependency some day.
This also drops the possibility to call the constructor with null ~~and adds the possibility to call it with variable length arguments (as some similar constructors and add methods already do)~~.
This is split from #416.

Add SnakList constructor

---

src/HashArray.php
src/Snak/SnakList.php
tests/unit/HashArray/HashArrayWithoutDuplicatesTest.php
tests/unit/Snak/SnakListTest.php

This goes along with #713 (and will run into a merge conflict – feel free to merge whichever first, I will do the rebase). Both are split from #702 to make that big patch it easier to review later.
Note that I rewrote the tests entirely. This is also the main reason for this patch, to make sure SnakList is properly covered with tests before we are applying the big change in #702.

Move Hashable interface from HashArray to SnakList

---

src/ReferenceList.php
tests/unit/ReferenceListTest.php

This behavior was inconsistent at least since 4.x, if not forever. I added these tests just recently in #641. They tested the current, but undocumented (and I believe unintentional) behavior: When adding the **same** reference a second time, it was possible to move it to a position with a smaller index, but not to a higher index. My first attempt was to fix the later. After reconsideration I'm now removing this reindexing feature entirely.
Technically breaking, but unused and therefore of no consequence in our relevant code bases.

Remove reindexing feature from ReferenceList::addReference

---

src/HashArray.php
src/Snak/SnakList.php
tests/unit/HashArray/HashArrayTest.php
tests/unit/Snak/SnakListTest.php

This goes along with #714 (and will run into a merge conflict – feel free to merge whichever first, I will do the rebase). Both are split from #702 to make that big patch it easier to review later.
Note that I rewrote the tests entirely. This is also the main reason for this patch, to make sure SnakList is properly covered with tests before we are applying the big change in #702.

Move HashArray::equals to SnakList::equals

---

RELEASE-NOTES.md
WikibaseDataModel.php
composer.json
mediawiki-extension.json
src/Entity/EntityIdValue.php
src/Entity/ItemId.php
src/Entity/PropertyId.php
src/Snak/PropertyValueSnak.php
src/Snak/SnakObject.php
src/Statement/StatementList.php
src/Term/AliasGroupList.php
src/Term/TermList.php

Please have a look at the milestone before merging this: https://github.com/wmde/WikibaseDataModel/milestone/20
[Bug: T157965](https://phabricator.wikimedia.org/T157965)

Release 7.0.0

---

src/Snak/SnakList.php

This accidentally happened in #714.

Fix bad see tag in SnakList

---

tests/unit/Snak/SnakListTest.php

This is a super tiny refactoring step split from #702. Note that this class name is not dynamic. It always is "SnakList".

Do not use dynamic class name in SnakListTest

---

tests/unit/HashArray/HashArrayTest.php
tests/unit/HashArray/HashArrayWithoutDuplicatesTest.php
tests/unit/Snak/SnakListTest.php

All I do here is inlining the three methods from the abstract base class into the two implementations.
You will notice that the base class is almost empty now. A single helper method is left, and this is even used by only one of the two implementations. I'm aware of this, but I stopped working on the code at this point on purpose to make this patch as trivial as it can be. #702 will get rid of the base class along with the second implementation. There is just no point in making this code nicer before killing it.
This patch does the following things:
* It moves all relevant code to `SnakListTest`, making it more robust. This is the test we really care about.
* It removes a redundant test case from `SnakListTest`. Before, it was creating two instances with no arguments and `[]`. These are …

Inline all abstract stuff from HashArrayTest to the implementations

---

src/Entity/EntityIdValue.php
tests/fixtures/CustomEntityId.php
tests/unit/Entity/EntityIdValueTest.php

We need EntityIdValues to support plain old PHP serialization, so we can put objects that contain EntityIdValues into the object cache. 
This changes does two things:
* add tests that make sure we can apply PHP serialization and JSON serialization fr custom and foreign entity types
* Add support for JSON serialization of entity types IDs the not have a numeric representation.
Bug: https://phabricator.wikimedia.org/T160516

Improve serialization support for custom ID types and foreign IDs.

---

Aliases.php
composer.json
phpcs.xml
src/HashArray.php
src/Term/AliasGroupList.php
src/Term/TermList.php
tests/unit/HashArray/HashArrayWithoutDuplicatesTest.php
tests/unit/Snak/SnakListTest.php

I did a diff of what `phpcs -e` ("explain a standard by showing the sniffs it includes") outputs before and after the changes I'm doing in this patch:
* A series of 5 `Generic.CodeAnalysis.…` rules is added.
* `Generic.Formatting.MultipleStatementAlignment` is new.
* 12 `MediaWiki.…` are added.
* `Squiz.ControlStructures.ControlSignature` is new.
* `Squiz.Classes.DuplicateProperty` is removed. This is fine, because this is a JavaScript-only sniff that was included by mistake.

Switch to the Wikibase CodeSniffer rule set

---

.travis.yml
phpcs.xml

The changes I made in #745 accidentally removed crucial exclude patterns.
Having these additional sniffs here, locally, and not in the Wikibase rule set, is intended exactly because of these exceptions.

Fix broken PHPCS rule set

---

src/Entity/Item.php
tests/unit/Entity/ItemTest.php

Unused. Fixes #733. Also see #734.

Remove deprecated Item::getSiteLinks

---

tests/unit/Entity/EntityIdValueTest.php

This was originally part of #728. The idea of removing these test cases is that testing with a minimal and a larger ID should be enough. The other test cases do not add anything new.

Remove redundant EntityIdValue test cases

---

tests/unit/Entity/ItemTest.php
tests/unit/Entity/PropertyTest.php
tests/unit/Term/AliasGroupFallbackTest.php
tests/unit/Term/AliasGroupTest.php
tests/unit/Term/TermFallbackTest.php
tests/unit/Term/TermTest.php

This is especially critical if the expected result is an empty string.

Update some assertEquals to more safe assertSame

---

src/Entity/Item.php

Unused. The replacement is much more expressive, in my opinion:
```php
$item->getSiteLinkList()->isEmpty()
```
See #734.

Remove deprecated Item::hasSiteLinks

---

src/Entity/Item.php

They where deprecated years ago and never removed, presumably cause there is no clear motivation to do so.
IIRC I deprecated this stuff, but at present I no longer think this makes things better.
Note that this leaves one of them in place (since I do think that one does not make sense to have here): https://github.com/wmde/WikibaseDataModel/issues/733

Undeprecate SiteLink methods in Item

---

src/Entity/EntityDocument.php

This does not make much of a difference for the existing Item and Property entity types. But it became relevant for the Lexeme entity type. In the Lexeme class we made it possible to have nullable constructor parameters, but the corresponding setters do not allow null. This means there are fields that can never be removed from an existing entity that had these fields set before. This becomes relevant when trying to merge two Lexemes. The code doing the merge checks if the old Lexeme was emptied first, and rejects the merge otherwise.
TL;DR: isEmpty does not make much sense if there is no way to empty an entity.

Clarify contract of EntityDocument::isEmpty

---

src/Statement/StatementGuid.php
tests/unit/Entity/EntityRedirectTest.php
tests/unit/Statement/StatementGuidTest.php

The only caller is in StatementGuidParser, and the function argument is guaranteed to be of this type there. No other caller exists (outside of tests).
I believe this was a mistake or fragment from a time where strict type hints did not existed.

Add strict type hint to StatementGuid constructor

---

src/Entity/Item.php
src/Entity/Property.php

Introduced in #753.
Three people discussed there, and a fourth person noticed this mistake, but 5 days later nobody was able to fix it. I find this quite fascinating.
I agree with Jeroen in so far that the removal done in #753 was not required to fulfill what the ticket asked for: it's perfectly possible to **not** call `setId` with integers, even if the method still accepts integers. However, it's obviously much easier to find unwanted usages if `setId` fails with an exception if ever called with an integer.
The only downside of the removal is that test code becomes harder to write. I agree that calls like `$item->setId( 1 )` must be burned with fire. But `$item->setId( new ItemId( 'Q1' ) )` is quite ugly. What about allowing `$item->setId( 'Q1' )`? Is this worth it? (I know we already …

Fix forgotten Item/Property::setId documentation and exception

---

phpcs.xml
phpmd.xml

This uses the current limits of the actual code base for all numeric PHPCS and PHPMD rules. This does have two effects. First, now the rule sets reflect the actual state of the code.
Second, whenever a commit introduces code that's more complex than what's currently in this component, we will be aware of that. In most cases we will simply raise the limit in the same commit. So this is not about blocking such commits. It should be allowed to raise these limits if it makes sense. This is about awareness.
Also see https://github.com/wmde/WikibaseDataModelServices/pull/101.

Use current lower limits for PHPCS and MD

---

src/Entity/DispatchingEntityIdParser.php

This made the function quite a bit faster:
> 14.48% 48797.778 817218 - Wikibase\DataModel\Entity\DispatchingEntityIdParser::parse
to
> 12.64% 42330.389 817218 - Wikibase\DataModel\Entity\DispatchingEntityIdParser::parse
when JSON-dumping 10,000 Wikidata entities.
Related to https://phabricator.wikimedia.org/T177486.

Optimized DispatchingEntityIdParser

---

src/Term/TermList.php

Without this type hint we get an IDE error (and probably further static analysis errors) as
SpecialNewLexeme::createSummary calls getIterator and calls current() on the result
which doesn't exist in the current typehint.
This is a 2 part fix, getIterator should document that it can return an Iterator, and also
the createSummary method should probably check that it actually has a Iterator instead
of a just a Traversable.

phpdoc: TermList::getIterator can return an Iterator

---

src/Entity/ItemId.php
src/Entity/PropertyId.php

* Remove two is_string checks that are effectively dead code. The variable is coming from a splitSerialization call, which is guaranteed to return strings. And even if, the next preg_match check will still catch all errors.
* I move the strtoupper down, mostly for performance reasons.
* The shorter variable name $parts makes this much better readable. Before, this short method repeated the word "serialization" 8 times.

Streamline ItemId and PropertyId constructors a little

---

src/Term/TermList.php

* phpdoc: TermList::getIterator can return an Iterator
Without this type hint we get an IDE error (and probably further static analysis errors) as
SpecialNewLexeme::createSummary calls getIterator and calls current() on the result
which doesn't exist in the current typehint.
This is a 2 part fix, getIterator should document that it can return an Iterator, and also
the createSummary method should probably check that it actually has a Iterator instead
of a just a Traversable.
* Remove Traversable from getIterator phpdoc

phpdoc: TermList::getIterator can return an Iterator (#774)

---

.phpcs.xml
tests/unit/ReferenceListTest.php

* I'm always trying to reduce the line length in tiny steps, to have diffs that are as small and as easy to review as possible.
* The removed CamelCapsFunctionName sniff is obsolete. This is already covered by two other sniffs.
* The ArrayBracketSpacing sniff is in conflict with the MediaWiki code style that suggests to use spaces inside `$array[ $index ]`. We should not enforce a conflicting style. For now, both is allowed.

Reduce line length and simplify PHPCS rule set

---

tests/unit/Entity/ItemTest.php
tests/unit/Entity/PropertyTest.php

I'm not sure how this happened, but this is what these two tests did:
* Create an empty entity.
* Set some aliases as provided. The provider only provides some "en" and "de" aliases.
* Set "zh" and "zu" aliases.
* Compare the "en" and "de" aliases.
That's all. It never checked what happened with the "zh" and "zu" aliases.

Fix broken Item and Property::testSetEmptyAlias tests

---

src/Entity/Item.php
src/Entity/Property.php
src/Entity/StatementListProvidingEntity.php

This interface allows for better type hinting when expecting an `EntityDocument` that has statements, e.g. when merging two lists of statements.
Examples where this would be useful: 
https://gerrit.wikimedia.org/r/c/mediawiki/extensions/Wikibase/+/448026/3/repo/includes/Merge/Validator/NoCrossReferencingStatements.php#21
https://gerrit.wikimedia.org/r/c/mediawiki/extensions/Wikibase/+/447084/8/repo/includes/Merge/StatementsMerger.php#30
Note: I do realize that `Item` and `Property` do not directly implement `StatementListProvider`, but `StatementListHolder`. `Lexeme`, `Form` and `Sense` implement only `StatementListProvider`. This makes it a little awkward.
Task on Phab: https://phabricator.wikimedia.org/T200024

Introduce StatementListProvidingEntity interface

---

src/Term/TermList.php
tests/unit/Term/TermListTest.php

So TermListMerger in WikibaseLexeme can be removed
Note that TermListMerger does a not needed hasTerm check which has been omitted here

Add TermList::add

---

tests/unit/Term/AliasGroupListTest.php

- Use more strict `assertSame` whenever possible.
- ~~Use isEmpty when possible, instead of comparing objects.~~
- In `testGivenEmptyGroups_constructorRemovesThem` two objects were compared, but it was never checked if they are empty.

Simplify and clean up AliasGroupListTest assertions

---

RELEASE-NOTES.md
src/Entity/Item.php
src/Entity/Property.php

This completes/fixes the revert started in https://github.com/wmde/WikibaseDataModel/pull/799
With this change the behavior is back to that of DM 7.5.x. (see https://github.com/wmde/WikibaseDataModel/blob/7.x/src/Entity/Item.php#L30 for verification)
Needed to make DM 9.x work in WB.git. Change in behavior spotted by WB.git tests

Fix earlier ClearbaleEntity revert

---

.travis.yml
composer.json

Upgrade wikimedia/assert to 0.4.0 (no major changes but needed to avoid incompatible dependencies in mediawiki/vendor). Upgrade PHP requirement to 7.x or HHVM (needed by wikimedia/assert 0.4 and the end-of-life for 5.6 was January 1, anyway).

Update wikimedia/assert, minimum PHP version

---

RELEASE-NOTES.md
src/Entity/EntityId.php

When this method was first introduced, `getRepositoryName()` would split the serialization each time it was called, and using `strpos()` in `isForeign()` was an optimization to avoid that cost. However, since #769 (commit eb6656155b), the serialization is only split once in the constructor, so checking `strpos` each time instead of deferring to the already populated `$repositoryName` is probably slightly more expensive.
As a very minor optimization, we directly access `$this->repositoryName` instead of calling `getRepositoryName()`. Subclasses that for some reason override `getRepositoryName()` to do something different must override `isForeign()` as well.

Optimize EntityId::isForeign()

---

src/Entity/StatementListProvidingEntity.php

There never was a 7.6 release, its changes were combined with breaking changes into 8.0 instead.

Fix @since of StatementListProvidingEntity

---

src/Entity/ItemIdSet.php
src/ReferenceList.php
src/SiteLinkList.php
src/Statement/StatementByGuidMap.php
src/Statement/StatementList.php
src/Term/AliasGroupList.php

This change of type hints from Traversable to Iterator avoids static
analysis errors by phan. As described in
https://github.com/phan/phan/blob/master/NEWS.md#11-feb-2018-phan-0112
phan's type system still does not support inferring key types for
Iterable or Traversable.

Change getIterator() type hints to Iterator

---

RELEASE-NOTES.md
src/Term/TermTypes.php

Useful when passing term types to services like TermBuffer.

Add TermTypes interface with term type constants

---

RELEASE-NOTES.md
src/Statement/StatementGuid.php
tests/unit/Statement/StatementGuidTest.php

This would be useful for reconstructing another StatementGuid based on its existing parts.
EntityId can already be gotten from a StatementGuid object, and now the GUID would too - that's the 2 required arguments for constructing a new StatementGuid with the same (or derived) data.
Use case: https://gerrit.wikimedia.org/r/c/mediawiki/extensions/WikibaseMediaInfo/+/573315/1/src/WikibaseMediaInfoHooks.php

Add getter for statement guid part

---

phpmd.xml
src/ReferenceList.php
src/Snak/SnakList.php
tests/unit/ReferenceListTest.php

PHP 7.4 exposes two new magic functions __serialize and __unserialize
for custom object serialization. These are required to be implemented to
support migration from older PHP versions.
see https://wiki.php.net/rfc/custom_object_serialization for more
detail.
Bug: T243590

WikibaseDataModel: PHP 7.4 CI fails

---

tests/unit/ReferenceTest.php
tests/unit/Statement/StatementTest.php

Reviewed and added tests for the missing ones.
ReferenceList: exists
Statement: new
Reference: new
SnakList: exists
SnakObject
- DerivedPropertyValueSnakTest: exists
- PropertyNoValueSnakTest: exists
- PropertySomeValueSnakTest: exists
- PropertyValueSnakTest: exists
Bug: T253637
https://phabricator.wikimedia.org/T253637

Ensure hash stability

---

.gitignore

As part of removing interface usages for the release of DataValues, I noticed this file was not ignored.

Ignore phpunit tests result cache

---

RELEASE-NOTES.md
src/Internal/MapValueHasher.php
src/Reference.php
src/Snak/Snak.php
src/Snak/SnakList.php
src/Snak/SnakObject.php
src/Statement/Statement.php
tests/unit/ReferenceListTest.php
tests/unit/Snak/SnakListTest.php

Removes interface usages as they were blocking the [release of DataValues/DataValues v 3.0.0](https://github.com/DataValues/DataValues/issues/58#issuecomment-700998895)
Related to: [T260915](https://phabricator.wikimedia.org/T260915)

Retire interfaces

---

src/SiteLinkList.php
src/Statement/StatementList.php

psalm in my own project complains about this issue, as `Iterator` is missing a use statement
Noticed in https://github.com/addwiki/addwiki/pull/48

Lists mostly need a use Iterator;

---

src/Entity/EntityRedirect.php

This will make trackng down the source of such exceptions from
MediaWiki instances easier.

log the errant entityId and targetId in entityRedirect exceptions

---

RELEASE-NOTES.md
src/Snak/Snak.php

The Snak interface used to implement the Hashable and Comparable interfaces
which had `getHash` and `equals` functions.
We need those for avoid a bunch of errors in Wikibase.

Fix Snak interface
